# Generated by Django 4.0.3 on 2022-03-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='log',
            new_name='par',
        ),
    ]
