# Generated by Django 4.0.3 on 2022-03-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0003_rename_log_people_par'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
