# Generated by Django 4.0.3 on 2022-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0004_delete_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamni',
            name='ss',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kamni',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kamni',
            name='task',
            field=models.TextField(),
        ),
    ]
